const express=require('express')
const user_autheticate=require('../authentication')
const router=express.Router()
const user_controller= require('../controller/user')
const user_group=require('../controller/user_group')
const user_group_chat=require('../controller/group_chat')
router.post('/signup',user_controller.signup)
router.post('/login',user_controller.login)
router.post('/group',user_autheticate.authenticate,user_group.group)
router.get('/group_chat',user_group.group_chat)
router.post('/group_chat',user_autheticate.authenticate,user_group.group_chat_post)
router.get('/getgroup',user_autheticate.authenticate,user_group.getgroup)
module.exports=router